// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvWjkza0-KIjTG0vk3gBkB4CC6tSyRYwQ',
    appId: '1:947945457722:android:8ea0f28d55f8e9814f4d03',
    messagingSenderId: '947945457722',
    projectId: 'faster-5dd74',
    databaseURL: 'https://faster-5dd74.firebaseio.com',
    storageBucket: 'faster-5dd74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2B7-iK4IlO0yQZk0HTjZyTAZlXFQUCj8',
    appId: '1:947945457722:ios:ed29d038621923d94f4d03',
    messagingSenderId: '947945457722',
    projectId: 'faster-5dd74',
    databaseURL: 'https://faster-5dd74.firebaseio.com',
    storageBucket: 'faster-5dd74.appspot.com',
    androidClientId: '947945457722-oa0hentt8i4us6b63fq1ho1sbaippjq4.apps.googleusercontent.com',
    iosBundleId: 'com.jayeeapp.taxi',
  );
}
